# Generated by Django 6.0.4 on 2026-04-09 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
            },
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Fase de Grupos, Quartas de Final, Final', max_length=100)),
                ('tipo', models.CharField(choices=[('GRUPO', 'Fase de Grupos'), ('ELIMINATORIA', 'Fase Eliminatória')], max_length=20)),
                ('ordem', models.PositiveIntegerField(default=1, help_text='Ordem de execução das fases no torneio')),
                ('equipes_avancam', models.PositiveIntegerField(default=2, help_text='Quantas equipes de cada grupo avançam para a próxima fase.')),
            ],
            options={
                'verbose_name': 'Fase',
                'verbose_name_plural': 'Fases',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='RegraPontuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Set Único 21pts, Melhor de 3 com 15pts', max_length=100)),
                ('sets_para_vencer', models.PositiveIntegerField(default=1, help_text='Quantos sets precisa vencer para ganhar a partida. Ex: 1 para set único, 2 para melhor de 3.')),
                ('pontos_por_set', models.PositiveIntegerField(default=21, help_text='Pontos para fechar o set')),
                ('tem_vantagem', models.BooleanField(default=True, help_text='Se True, precisa abrir 2 pontos de vantagem para vencer o set.')),
                ('limite_pontos_diretos', models.PositiveIntegerField(blank=True, help_text='Se preenchido, ao atingir este valor o time vence direto sem precisar de vantagem. Ex: 18 num set de 15.', null=True)),
            ],
            options={
                'verbose_name': 'Regra de Pontuação',
                'verbose_name_plural': 'Regras de Pontuação',
            },
        ),
        migrations.CreateModel(
            name='Torneio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('modalidade', models.CharField(help_text='Ex: Vôlei de Praia, Beach Tennis', max_length=100)),
                ('local', models.CharField(max_length=255)),
                ('data_inicio', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('jogadores_por_equipe', models.PositiveIntegerField(default=2)),
                ('status', models.CharField(choices=[('CRIACAO', 'Criação'), ('INSCRICOES', 'Inscrições'), ('ANDAMENTO', 'Em Andamento'), ('ENCERRADO', 'Encerrado')], default='CRIACAO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Torneio',
                'verbose_name_plural': 'Torneios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Grupo A, Grupo 1', max_length=50)),
                ('equipes', models.ManyToManyField(blank=True, related_name='grupos', to='core.equipe')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='core.fase')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
            },
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('apelido', models.CharField(blank=True, max_length=50)),
                ('posicao', models.CharField(blank=True, max_length=50)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogadores', to='core.equipe')),
            ],
            options={
                'verbose_name': 'Jogador',
                'verbose_name_plural': 'Jogadores',
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('AO_VIVO', 'Ao Vivo'), ('FINALIZADA', 'Finalizada')], default='AGENDADA', max_length=20)),
                ('is_wo', models.BooleanField(default=False, help_text='Se True, vitória por W.O. com pontuação máxima automática.')),
                ('ordem_cronograma', models.PositiveIntegerField(default=0, help_text='Ordem de disputa na quadra única.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipe_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_como_a', to='core.equipe')),
                ('equipe_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_como_b', to='core.equipe')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='core.fase')),
                ('grupo', models.ForeignKey(blank=True, help_text='Preenchido apenas em fases de grupo.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='core.grupo')),
                ('vencedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitorias', to='core.equipe')),
                ('vencedor_wo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitorias_wo', to='core.equipe')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
                'ordering': ['ordem_cronograma'],
            },
        ),
        migrations.AddField(
            model_name='fase',
            name='regra',
            field=models.ForeignKey(help_text='Regra de pontuação aplicada a todas as partidas desta fase.', on_delete=django.db.models.deletion.PROTECT, to='core.regrapontuacao'),
        ),
        migrations.CreateModel(
            name='SetResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_set', models.PositiveIntegerField(help_text='Número do set. Ex: 1, 2, 3')),
                ('pontos_a', models.PositiveIntegerField(default=0)),
                ('pontos_b', models.PositiveIntegerField(default=0)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='core.partida')),
            ],
            options={
                'verbose_name': 'Set',
                'verbose_name_plural': 'Sets',
                'ordering': ['numero_set'],
            },
        ),
    ]
