# Generated by Django 6.0.4 on 2026-04-09 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='torneio',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torneios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fase',
            name='torneio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases', to='core.torneio'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='torneio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='core.torneio'),
        ),
        migrations.AlterUniqueTogether(
            name='setresult',
            unique_together={('partida', 'numero_set')},
        ),
        migrations.AlterUniqueTogether(
            name='equipe',
            unique_together={('torneio', 'nome')},
        ),
    ]
