# Generated by Django on 2026-04-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='rodada',
            field=models.PositiveIntegerField(default=1, help_text='Número da rodada dentro da fase (1=primeira rodada)'),
        ),
    ]
