# Generated by Django 5.2.13 on 2026-04-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_partida_rodada'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneio',
            name='formato_torneio',
            field=models.CharField(blank=True, choices=[('grupos_e_eliminatoria', 'Grupos + Eliminatória'), ('so_eliminatoria', 'Só Eliminatória')], help_text='Formato de disputa do torneio', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='torneio',
            name='quantidade_times',
            field=models.PositiveIntegerField(blank=True, choices=[(4, '4 times'), (8, '8 times'), (16, '16 times'), (32, '32 times')], help_text='Quantidade total de times no torneio', null=True),
        ),
        migrations.AddField(
            model_name='torneio',
            name='times_por_grupo',
            field=models.PositiveIntegerField(choices=[(4, '4 times por grupo')], default=4, help_text='Quantidade de times por grupo (apenas para grupos_e_eliminatoria)'),
        ),
    ]
