# Generated by Django 5.2.13 on 2026-04-13 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_torneio_formato_torneio_torneio_quantidade_times_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase',
            name='regra',
            field=models.ForeignKey(blank=True, help_text='Regra de pontuação aplicada a todas as partidas desta fase.', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.regrapontuacao'),
        ),
    ]
