# Generated by Django 6.0.4 on 2026-04-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fase_is_ativa_torneio_live_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='celular',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='jogador',
            name='tamanho_camisa',
            field=models.CharField(blank=True, choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('3G', '3G')], max_length=2),
        ),
    ]
